# Generated by Django 6.0.1 on 2026-01-23 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_candidato_id_alter_candidatohabilidad_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='accounts.candidato'),
        ),
    ]
