# Generated by Django 4.2.27 on 2026-01-26 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_alter_ciudad_id_alter_pais_id_alter_provincia_id'),
        ('accounts', '0006_alter_candidato_id_alter_candidatohabilidad_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_contrato', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('freelance', 'Freelance'), ('pasantia', 'Pasantía'), ('temporal', 'Temporal'), ('por_proyecto', 'Por Proyecto')], default='tiempo_completo', max_length=50)),
                ('modalidad', models.CharField(blank=True, help_text='Presencial, Remoto, Híbrido', max_length=100, null=True)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada'), ('expirada', 'Expirada')], default='borrador', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.categoria')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_jobs', to='accounts.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OfertasGuardadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_guardadas', to='accounts.candidato')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.ofertaempleo')),
            ],
            options={
                'verbose_name': 'Oferta Guardada',
                'verbose_name_plural': 'Ofertas Guardadas',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('visto', 'Visto'), ('entrevista', 'Entrevista'), ('prueba_tecnica', 'Prueba Técnica'), ('oferta', 'Oferta'), ('rechazado', 'Rechazado'), ('contratado', 'Contratado'), ('retirado', 'Retirado')], default='pendiente', max_length=20)),
                ('feedback_empresa', models.TextField(blank=True, help_text='Opcional: Feedback al rechazar', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='accounts.candidato')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='jobs.ofertaempleo')),
            ],
            options={
                'verbose_name_plural': 'Postulaciones',
                'unique_together': {('oferta', 'candidato')},
            },
        ),
        migrations.CreateModel(
            name='OfertaHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_requerido', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='basico', max_length=20)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.habilidad')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_requeridas', to='jobs.ofertaempleo')),
            ],
            options={
                'unique_together': {('oferta', 'habilidad')},
            },
        ),
    ]
