# Generated by Django 6.0 on 2026-01-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ofertahabilidad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ofertahabilidad',
            name='nivel',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='intermedio', max_length=50),
        ),
        migrations.AddField(
            model_name='ofertahabilidad',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='Requisito / Habilidad'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ofertahabilidad',
            name='habilidad',
        ),
        migrations.RemoveField(
            model_name='ofertahabilidad',
            name='nivel_requerido',
        ),
    ]
