# Generated by Django 4.2.27 on 2026-01-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_categoria_id_alter_ofertaempleo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'candidatos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'habilidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ofertaempleo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ofertahabilidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ofertasguardadas',
            options={'managed': False, 'verbose_name': 'Oferta Guardada', 'verbose_name_plural': 'Ofertas Guardadas'},
        ),
        migrations.AlterModelOptions(
            name='postulacion',
            options={'managed': False, 'verbose_name_plural': 'Postulaciones'},
        ),
    ]
