# Generated by Django 4.2.27 on 2026-01-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_candidato_ciudad_empresa_habilidad_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidato',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ofertaempleo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ofertahabilidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ofertasguardadas',
            options={'verbose_name': 'Oferta Guardada', 'verbose_name_plural': 'Ofertas Guardadas'},
        ),
        migrations.AlterModelOptions(
            name='postulacion',
            options={'verbose_name_plural': 'Postulaciones'},
        ),
    ]
