# Generated by Django 4.2.27 on 2026-01-26 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_candidato_id_alter_candidatohabilidad_id_and_more'),
        ('jobs', '0006_delete_empresa_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertasguardadas',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_guardadas', to='accounts.candidato'),
        ),
    ]
