# Generated by Django 5.2.8 on 2026-01-22 22:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Java, SQL, Excel', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Inglés, Francés', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('tipo_usuario', models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa'), ('admin', 'Administrador')], max_length=20)),
                ('estado', models.BooleanField(default=True, help_text='true=activo, false=baneado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(help_text='Para calcular la edad automáticamente')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20, null=True)),
                ('numero_identificacion', models.CharField(blank=True, help_text='Cédula, DNI o Pasaporte', max_length=50, null=True, unique=True)),
                ('foto_perfil_url', models.CharField(blank=True, help_text='URL a la foto del usuario', max_length=500, null=True)),
                ('titulo_profesional', models.CharField(blank=True, help_text='Ej: Desarrollador Backend Junior', max_length=200, null=True)),
                ('resumen_perfil', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('salario_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disponibilidad', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.ciudad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('url_archivo', models.CharField(max_length=500)),
                ('tipo_documento', models.CharField(help_text='CV, Carta, Certificado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='accounts.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('nivel', models.CharField(help_text='Bachiller, Tercer Nivel, Maestría', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(help_text='En curso, Graduado, Trunco', max_length=50)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='accounts.candidato')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, help_text='URL al bucket S3 o carpeta media', max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.ciudad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('trabajo_actual', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_laboral', to='accounts.candidato')),
            ],
            options={
                'verbose_name_plural': 'Experiencias Laborales',
            },
        ),
        migrations.CreateModel(
            name='CandidatoHabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='accounts.candidato')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.habilidad')),
            ],
            options={
                'unique_together': {('candidato', 'habilidad')},
            },
        ),
        migrations.CreateModel(
            name='CandidatoIdioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(help_text='A1, A2, B1, B2, C1, C2, Nativo', max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='accounts.candidato')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.idioma')),
            ],
            options={
                'unique_together': {('candidato', 'idioma')},
            },
        ),
    ]
