# Generated by Django 5.2.8 on 2026-01-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_documento_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='descripcion_empresa',
            field=models.TextField(blank=True, help_text='Breve descripción del sector y tamaño', null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='logros',
            field=models.TextField(blank=True, help_text='Resultados cuantificables', null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='motivo_salida',
            field=models.TextField(blank=True, help_text='Solo control interno', null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='personas_cargo',
            field=models.IntegerField(blank=True, help_text='Número de personas a cargo', null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='proyectos_destacados',
            field=models.URLField(blank=True, help_text='Enlace a portafolio o proyecto', null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='tecnologias',
            field=models.CharField(blank=True, help_text='Herramientas usadas', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='tipo_contrato',
            field=models.CharField(blank=True, help_text='Freelance, Nominal, etc', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ciudad y País', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidatohabilidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidatoidioma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Funciones principales', null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar vacío si es actual', null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
