# Generated by Django 5.2.8 on 2026-01-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_experiencialaboral_descripcion_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatohabilidad',
            name='anios_experiencia',
            field=models.PositiveIntegerField(default=0, help_text='Años de experiencia aplicando esta habilidad'),
        ),
        migrations.AddField(
            model_name='candidatohabilidad',
            name='contexto_uso',
            field=models.TextField(blank=True, help_text='En qué proyecto o empresa la utilizaste', null=True),
        ),
    ]
