# Generated by Django 4.2.27 on 2026-01-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_candidato_id_alter_candidatohabilidad_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa')], max_length=20),
        ),
    ]
