# Generated by Django 4.2.27 on 2026-01-26 23:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa'), ('admin', 'Admin')], max_length=20)),
                ('estado', models.BooleanField(default=True, help_text='true=activo, false=baneado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(help_text='Para calcular la edad automáticamente')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20, null=True)),
                ('numero_identificacion', models.CharField(blank=True, help_text='Cédula, DNI o Pasaporte', max_length=50, null=True, unique=True)),
                ('foto_perfil_url', models.CharField(blank=True, help_text='URL a la foto del usuario', max_length=500, null=True)),
                ('titulo_profesional', models.CharField(blank=True, help_text='Ej: Desarrollador Backend Junior', max_length=255, null=True)),
                ('resumen_perfil', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('salario_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disponibilidad', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=500, null=True)),
                ('github_url', models.CharField(blank=True, max_length=500, null=True)),
                ('portfolio_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'candidatos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, help_text='URL al bucket S3 o carpeta media', max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.ForeignKey(blank=True, db_column='ciudad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolsa_empleo.ciudad')),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Java, SQL, Excel', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
                'db_table': 'habilidades',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Inglés, Francés', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'idiomas',
            },
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_contrato', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('freelance', 'Freelance'), ('pasantia', 'Pasantía'), ('temporal', 'Temporal'), ('por_proyecto', 'Por Proyecto')], default='tiempo_completo', max_length=50)),
                ('modalidad', models.CharField(blank=True, help_text='Presencial, Remoto, Híbrido', max_length=100, null=True)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada'), ('expirada', 'Expirada')], default='borrador', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolsa_empleo.categoria')),
                ('ciudad', models.ForeignKey(blank=True, db_column='ciudad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolsa_empleo.ciudad')),
                ('empresa', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='bolsa_empleo.empresa')),
            ],
            options={
                'db_table': 'ofertas_empleo',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iso', models.CharField(help_text='Ej: EC, MX', max_length=2)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='bolsa_empleo.pais')),
            ],
        ),
        migrations.CreateModel(
            name='OfertasGuardadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidato', models.ForeignKey(db_column='candidato_id', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_guardadas', to='bolsa_empleo.candidato')),
                ('oferta', models.ForeignKey(db_column='oferta_id', on_delete=django.db.models.deletion.CASCADE, to='bolsa_empleo.ofertaempleo')),
            ],
            options={
                'verbose_name': 'Oferta Guardada',
                'verbose_name_plural': 'Ofertas Guardadas',
                'db_table': 'ofertas_guardadas',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('trabajo_actual', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('candidato', models.ForeignKey(db_column='candidato_id', on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_laboral', to='bolsa_empleo.candidato')),
            ],
            options={
                'verbose_name_plural': 'Experiencias Laborales',
                'db_table': 'experiencia_laboral',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel', models.CharField(blank=True, help_text='Bachiller, Tercer Nivel, Maestría', max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, help_text='En curso, Graduado, Trunco', max_length=50, null=True)),
                ('candidato', models.ForeignKey(db_column='candidato_id', on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='bolsa_empleo.candidato')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
                'db_table': 'educacion',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('url_archivo', models.FileField(upload_to='documentos/')),
                ('tipo_documento', models.CharField(blank=True, help_text='CV, Carta, Certificado', max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidato', models.ForeignKey(db_column='candidato_id', on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='bolsa_empleo.candidato')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='bolsa_empleo.provincia'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='ciudad',
            field=models.ForeignKey(blank=True, db_column='ciudad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolsa_empleo.ciudad'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='usuario',
            field=models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('visto', 'Visto'), ('entrevista', 'Entrevista'), ('prueba_tecnica', 'Prueba Técnica'), ('oferta', 'Oferta'), ('rechazado', 'Rechazado'), ('contratado', 'Contratado'), ('retirado', 'Retirado')], default='pendiente', max_length=20)),
                ('feedback_empresa', models.TextField(blank=True, help_text='Opcional: Feedback al rechazar', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(db_column='candidato_id', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='bolsa_empleo.candidato')),
                ('oferta', models.ForeignKey(db_column='oferta_id', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='bolsa_empleo.ofertaempleo')),
            ],
            options={
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'postulaciones',
                'unique_together': {('oferta', 'candidato')},
            },
        ),
        migrations.CreateModel(
            name='OfertaHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_requerido', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='basico', max_length=20)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('habilidad', models.ForeignKey(db_column='habilidad_id', on_delete=django.db.models.deletion.CASCADE, to='bolsa_empleo.habilidad')),
                ('oferta', models.ForeignKey(db_column='oferta_id', on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_requeridas', to='bolsa_empleo.ofertaempleo')),
            ],
            options={
                'db_table': 'oferta_habilidad',
                'unique_together': {('oferta', 'habilidad')},
            },
        ),
        migrations.CreateModel(
            name='CandidatoIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(help_text='A1, A2, B1, B2, C1, C2, Nativo', max_length=20)),
                ('candidato', models.ForeignKey(db_column='candidato_id', on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='bolsa_empleo.candidato')),
                ('idioma', models.ForeignKey(db_column='idioma_id', on_delete=django.db.models.deletion.CASCADE, to='bolsa_empleo.idioma')),
            ],
            options={
                'db_table': 'candidato_idioma',
                'unique_together': {('candidato', 'idioma')},
            },
        ),
        migrations.CreateModel(
            name='CandidatoHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], max_length=20)),
                ('candidato', models.ForeignKey(db_column='candidato_id', on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='bolsa_empleo.candidato')),
                ('habilidad', models.ForeignKey(db_column='habilidad_id', on_delete=django.db.models.deletion.CASCADE, to='bolsa_empleo.habilidad')),
            ],
            options={
                'db_table': 'candidato_habilidad',
                'unique_together': {('candidato', 'habilidad')},
            },
        ),
    ]
